import StarProgress from "./StarProgress";

export const EnquiryData = [
  {
    sno: "1",
    enquiryno: "#24637",
    enquirydate: "11.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Truck",
  },
  {
    sno: "2",
    enquiryno: "#24638",
    enquirydate: "12.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Mini Truck",
  },
  {
    sno: "3",
    enquiryno: "#24639",
    enquirydate: "13.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Trailer",
  },
  {
    sno: "4",
    enquiryno: "#24640",
    enquirydate: "14.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Container Truck",
  },
  {
    sno: "5",
    enquiryno: "#24641",
    enquirydate: "18.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "6",
    enquiryno: "#24642",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "7",
    enquiryno: "#24643",
    enquirydate: "16.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },

  {
    sno: "8",
    enquiryno: "#24644",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "9",
    enquiryno: "#24645",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "10",
    enquiryno: "#24646",
    enquirydate: "25.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "11",
    enquiryno: "#24647",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Pickup Van",
  },
];

export const BookingData = [
  {
    sno: "1",
    enquiryno: "#24647",
    bookingcompany: "SwiftLogix",
    shippingdate: "11.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
  {
    sno: "2",
    enquiryno: "#24648",
    bookingcompany: "MoveMate",
    shippingdate: "12.02.2025",
    from: "name",
    to: "name",
    status: "in transmit",
    driver: "name",
  },
  {
    sno: "3",
    enquiryno: "#24649",
    bookingcompany: "TransFast",
    shippingdate: "13.02.2025",
    from: "name",
    to: "name",
    status: "completed",
    driver: "name",
  },
  {
    sno: "4",
    enquiryno: "#24650",
    bookingcompany: "FleetFlow",
    shippingdate: "14.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
  {
    sno: "5",
    enquiryno: "#24651",
    bookingcompany: "QuickHaul",
    shippingdate: "15.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
];

export const DailyData = [
  {
    sno: "1",
    vehicleno: "#24647",
    vehicletype: "Truck",
    currentlocationpincode: "600091",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Salem",
  },
  {
    sno: "2",
    vehicleno: "#24648",
    vehicletype: "Truck",
    currentlocationpincode: "600092",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Coimbatore",
  },
  {
    sno: "3",
    vehicleno: "#24649",
    vehicletype: "Truck",
    currentlocationpincode: "600093",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Salem,Coimbatore",
  },
  {
    sno: "4",
    vehicleno: "#24650",
    vehicletype: "Truck",
    currentlocationpincode: "600094 ",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Madurai",
  },
  {
    sno: "5",
    vehicleno: "#24651",
    vehicletype: "Truck",
    currentlocationpincode: "600095",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Madurai,Coimbatore,Salem",
  },
];

export const VehicleData = [
  {
    sno: "1",
    vehicletype: "Truck",
    vehiclemodel: "SwiftLogix",
    vehicleowner: "name",
    ownerphone: "8924647",
    vehicleno: "#24647",
    insurance: "824647",
  },
  {
    sno: "2",
    vehicletype: "Mini Truck",
    vehiclemodel: "MoveMate",
    vehicleowner: "name",
    ownerphone: "7824647",
    vehicleno: "#24648",
    insurance: "724647",
  },
  {
    sno: "3",
    vehicletype: "Trailer",
    vehiclemodel: "TransFast",
    vehicleowner: "name",
    ownerphone: "624647",
    vehicleno: "#24649",
    insurance: "85412",
  },
  {
    sno: "4",
    vehicletype: "Container Truck",
    vehiclemodel: "FleetFlow",
    vehicleowner: "name",
    ownerphone: "879456",
    vehicleno: "#24650",
    insurance: "324647",
  },
  {
    sno: "5",
    vehicletype: "Mini Truck",
    vehiclemodel: "QuickHaul",
    vehicleowner: "name",
    ownerphone: "23457",
    vehicleno: "#24651",
    insurance: "74102",
  },
];

export const DriverData = [
  {
    sno: "1",
    drivername: "name",
    phonenumber: "9874561230",
    address: "Madurai",
    license: "8924647",
    experience: "2years",
    ratings: <StarProgress rating={4.5} />,
  },
  {
    sno: "2",
    drivername: "name",
    phonenumber: "9784651230",
    address: "Salem",
    license: "8924647",
    experience: "3years",
    ratings: <StarProgress rating={1.75} />,
  },
  {
    sno: "3",
    drivername: "name",
    phonenumber: "9745681230",
    address: "Coimbatore",
    license: "8924647",
    experience: "4years",
    ratings: <StarProgress rating={2} />,
  },
  {
    sno: "4",
    drivername: "name",
    phonenumber: "874552309",
    address: "Madurai",
    license: "8924647",
    experience: "5years",
    ratings: <StarProgress rating={3} />,
  },
  {
    sno: "5",
    drivername: "name",
    phonenumber: "8564791230",
    address: "Salem",
    license: "8924647",
    experience: "2years",
    ratings: <StarProgress rating={4} />,
  },
];

export const InvoiceData = [
  {
    sno: "1",
    invoicenumber: "#24647",
    invoicedate: "11.02.2025",
    customername: "name",
    customercontact: "000000000",
    amountreceived: "567",
    amountpending: "58741",
  },
  {
    sno: "2",
    invoicenumber: "#24648",
    invoicedate: "12.02.2025",
    customername: "name",
    customercontact: "0000000",
    amountreceived: "567",
    amountpending: "65478",
  },
];

export const RevenueData = [
  {
    sno: "1",
    date: "11 .02. 2025",
    noofenquiry: "4",
    bidscount: "Count",
    bidaccepted: "5678",
    bidamount: "567",
  },
  {
    sno: "2",
    date: "14.02.2025",
    noofenquiry: "6",
    bidscount: "Count",
    bidaccepted: "5487",
    bidamount: "548",
  },
  {
    sno: "3",
    date: "14.02.2025",
    noofenquiry: "6",
    bidscount: "Count",
    bidaccepted: "5487",
    bidamount: "548",
  },
  {
    sno: "4",
    date: "14.02.2025",
    noofenquiry: "6",
    bidscount: "Count",
    bidaccepted: "5487",
    bidamount: "548",
  },
];

export const BookingReportData = [
  {
    sno: "1",
    date: "11.02.2025",
    bidaccepted: "5678",
    bidamount: "567",
    paymentcollected: "7894",
    paymentbalance: "7684",
  },
  {
    sno: "2",
    date: "14.02.2025",
    bidaccepted: "5487",
    bidamount: "548",
    paymentcollected: "5872",
    paymentbalance: "5678",
  },
];

export const TicketData = [
  {
    sno: "1",
    ticketid: "#24647",
    datacreated: "11.02.2025",
    category: "Delivery",
    priority: "high",
    status: "closed",
    assignedto: "Tanker",
    lastupdated: "14.02.2025",
  },
  {
    sno: "2",
    ticketid: "#24648",
    datacreated: "11.02.2025",
    category: "Delivery",
    priority: "low",
    status: "resolved",
    assignedto: "Mini Truck",
    lastupdated: "15.02.2025",
  },

  {
    sno: "3",
    ticketid: "#24648",
    datacreated: "15.02.2025",
    category: "Delivery",
    priority: "medium",
    status: "in progress",
    assignedto: "Truck",
    lastupdated: "18.02.2025",
  },
];

export const RoleData = [
  {
    sno: "1",
    name: "name",
    roles: "Admin",
    phonenumber: "7894561230",
    email: "test@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
];
