import StarProgress from "./StarProgress";

export const EnquiryData = [
  {
    sno: "1",
    enquiryno: "#24637",
    enquirydate: "13.03.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Truck",
  },
  {
    sno: "2",
    enquiryno: "#24638",
    enquirydate: "12.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Mini Truck",
  },
  {
    sno: "3",
    enquiryno: "#24639",
    enquirydate: "13.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Trailer",
  },
  {
    sno: "4",
    enquiryno: "#24640",
    enquirydate: "14.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Container Truck",
  },
  {
    sno: "5",
    enquiryno: "#24641",
    enquirydate: "18.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "6",
    enquiryno: "#24642",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "7",
    enquiryno: "#24643",
    enquirydate: "16.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },

  {
    sno: "8",
    enquiryno: "#24644",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "9",
    enquiryno: "#24645",
    enquirydate: "15.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
  {
    sno: "10",
    enquiryno: "#24646",
    enquirydate: "25.02.2025",
    goodstype: "Electronics & Appliances",
    weight: "56 Kg",
    from: "name",
    to: "name",
    vehicletype: "Tanker",
  },
];

export const BookingData = [
  {
    sno: "1",
    enquiryno: "#24647",
    bookingcompany: "SwiftLogix",
    shippingdate: "11.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
  {
    sno: "2",
    enquiryno: "#24648",
    bookingcompany: "MoveMate",
    shippingdate: "12.02.2025",
    from: "name",
    to: "name",
    status: "in transmit",
    driver: "name",
  },
  {
    sno: "3",
    enquiryno: "#24649",
    bookingcompany: "TransFast",
    shippingdate: "13.02.2025",
    from: "name",
    to: "name",
    status: "completed",
    driver: "name",
  },
  {
    sno: "4",
    enquiryno: "#24650",
    bookingcompany: "FleetFlow",
    shippingdate: "14.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
  {
    sno: "5",
    enquiryno: "#24651",
    bookingcompany: "QuickHaul",
    shippingdate: "15.02.2025",
    from: "name",
    to: "name",
    status: "confirmed",
    driver: "name",
  },
];

export const DailyData = [
  {
    sno: "1",
    vehicleno: "#24647",
    vehicletype: "Truck",
    currentlocationpincode: "600091",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Salem",
  },
  {
    sno: "2",
    vehicleno: "#24648",
    vehicletype: "Truck",
    currentlocationpincode: "600092",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Coimbatore",
  },
  {
    sno: "3",
    vehicleno: "#24649",
    vehicletype: "Truck",
    currentlocationpincode: "600093",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Salem,Coimbatore",
  },
  {
    sno: "4",
    vehicleno: "#24650",
    vehicletype: "Truck",
    currentlocationpincode: "600094 ",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Madurai",
  },
  {
    sno: "5",
    vehicleno: "#24651",
    vehicletype: "Truck",
    currentlocationpincode: "600095",
    preferredstate: "Tamilnadu",
    preferreddistrict: "Madurai,Coimbatore,Salem",
  },
];

export const VehicleData = [
  {
    sno: "1",
    vehicletype: "Truck",
    vehiclemodel: "SwiftLogix",
    vehicleowner: "name",
    ownerphone: "8924647",
    vehicleno: "#24647",
    insurance: "824647",
  },
  {
    sno: "2",
    vehicletype: "Mini Truck",
    vehiclemodel: "MoveMate",
    vehicleowner: "name",
    ownerphone: "7824647",
    vehicleno: "#24648",
    insurance: "724647",
  },
  {
    sno: "3",
    vehicletype: "Trailer",
    vehiclemodel: "TransFast",
    vehicleowner: "name",
    ownerphone: "624647",
    vehicleno: "#24649",
    insurance: "85412",
  },
  {
    sno: "4",
    vehicletype: "Container Truck",
    vehiclemodel: "FleetFlow",
    vehicleowner: "name",
    ownerphone: "879456",
    vehicleno: "#24650",
    insurance: "324647",
  },
  {
    sno: "5",
    vehicletype: "Mini Truck",
    vehiclemodel: "QuickHaul",
    vehicleowner: "name",
    ownerphone: "23457",
    vehicleno: "#24651",
    insurance: "74102",
  },
];

export const DriverData = [
  {
    sno: "1",
    drivername: "name",
    phonenumber: "9874561230",
    address: "Madurai",
    license: "8924647",
    experience: "2years",
    ratings: <StarProgress rating={4.5} />,
  },
  {
    sno: "2",
    drivername: "name",
    phonenumber: "9784651230",
    address: "Salem",
    license: "8924647",
    experience: "3years",
    ratings: <StarProgress rating={1.75} />,
  },
  {
    sno: "3",
    drivername: "name",
    phonenumber: "9745681230",
    address: "Coimbatore",
    license: "8924647",
    experience: "4years",
    ratings: <StarProgress rating={2} />,
  },
  {
    sno: "4",
    drivername: "name",
    phonenumber: "874552309",
    address: "Madurai",
    license: "8924647",
    experience: "5years",
    ratings: <StarProgress rating={3} />,
  },
  {
    sno: "5",
    drivername: "name",
    phonenumber: "8564791230",
    address: "Salem",
    license: "8924647",
    experience: "2years",
    ratings: <StarProgress rating={4} />,
  },
];

export const InvoiceData = [
  {
    sno: "1",
    invoicenumber: "#24647",
    invoicedate: "11.02.2025",
    customername: "name",
    customercontact: "000000000",
    amountreceived: "567",
    amountpending: "58741",
  },
  {
    sno: "2",
    invoicenumber: "#24648",
    invoicedate: "12.02.2025",
    customername: "name",
    customercontact: "0000000",
    amountreceived: "567",
    amountpending: "65478",
  },
];

export const BookingReports = [
  {
    sno: "1",
    date: "2025-03-13",
    noOfEnquiry: 15,
    bidsCount: 10,
    bidAccepted: 5,
    totalQuote: "$5000",
  },
  {
    sno: "2",
    date: "2025-03-14",
    noOfEnquiry: 20,
    bidsCount: 14,
    bidAccepted: 7,
    totalQuote: "$7500",
  },
  {
    sno: "3",
    date: "2025-03-15",
    noOfEnquiry: 18,
    bidsCount: 12,
    bidAccepted: 6,
    totalQuote: "$6200",
  },
  {
    sno: "4",
    date: "2025-03-16",
    noOfEnquiry: 25,
    bidsCount: 18,
    bidAccepted: 9,
    totalQuote: "$9100",
  },
  {
    sno: "5",
    date: "2025-03-17",
    noOfEnquiry: 22,
    bidsCount: 16,
    bidAccepted: 8,
    totalQuote: "$8400",
  },
  {
    sno: "6",
    date: "2025-03-18",
    noOfEnquiry: 17,
    bidsCount: 11,
    bidAccepted: 5,
    totalQuote: "$5700",
  },
  {
    sno: "7",
    date: "2025-03-19",
    noOfEnquiry: 30,
    bidsCount: 22,
    bidAccepted: 12,
    totalQuote: "$11000",
  },
  {
    sno: "8",
    date: "2025-03-20",
    noOfEnquiry: 28,
    bidsCount: 20,
    bidAccepted: 10,
    totalQuote: "$10200",
  },
  {
    sno: "9",
    date: "2025-03-21",
    noOfEnquiry: 19,
    bidsCount: 13,
    bidAccepted: 7,
    totalQuote: "$6800",
  },
  {
    sno: "10",
    date: "2025-03-22",
    noOfEnquiry: 24,
    bidsCount: 17,
    bidAccepted: 8,
    totalQuote: "$8900",
  },
];
export const RevenueReports = [
  {
    sno: "1",
    date: "2025-03-13",
    totalQuote: "$5000",
    quoteAmount: "$4500",
    paymentCollected: "$4000",
    paymentBalance: "$500",
  },
  {
    sno: "2",
    date: "2025-03-14",
    totalQuote: "$7500",
    quoteAmount: "$7000",
    paymentCollected: "$6500",
    paymentBalance: "$500",
  },
  {
    sno: "3",
    date: "2025-03-15",
    totalQuote: "$6200",
    quoteAmount: "$6000",
    paymentCollected: "$5500",
    paymentBalance: "$500",
  },
  {
    sno: "4",
    date: "2025-03-16",
    totalQuote: "$9100",
    quoteAmount: "$8800",
    paymentCollected: "$8000",
    paymentBalance: "$800",
  },
  {
    sno: "5",
    date: "2025-03-17",
    totalQuote: "$8400",
    quoteAmount: "$8200",
    paymentCollected: "$7800",
    paymentBalance: "$400",
  },
  {
    sno: "6",
    date: "2025-03-18",
    totalQuote: "$5700",
    quoteAmount: "$5500",
    paymentCollected: "$5000",
    paymentBalance: "$500",
  },
  {
    sno: "7",
    date: "2025-03-19",
    totalQuote: "$11000",
    quoteAmount: "$10500",
    paymentCollected: "$10000",
    paymentBalance: "$500",
  },
  {
    sno: "8",
    date: "2025-03-20",
    totalQuote: "$10200",
    quoteAmount: "$9800",
    paymentCollected: "$9400",
    paymentBalance: "$400",
  },
  {
    sno: "9",
    date: "2025-03-21",
    totalQuote: "$6800",
    quoteAmount: "$6600",
    paymentCollected: "$6200",
    paymentBalance: "$400",
  },
  {
    sno: "10",
    date: "2025-03-22",
    totalQuote: "$8900",
    quoteAmount: "$8600",
    paymentCollected: "$8100",
    paymentBalance: "$500",
  },
];

export const RejectionReports = [
  {
    sNo: 1,
    date: "2024-04-01",
    totalEnquiries: 50,
    quoted: 30,
    rejected: 20,
    rejectedPercentage: "40%",
  },
  {
    sNo: 2,
    date: "2024-04-02",
    totalEnquiries: 60,
    quoted: 35,
    rejected: 25,
    rejectedPercentage: "41.67%",
  },
  {
    sNo: 3,
    date: "2024-04-03",
    totalEnquiries: 55,
    quoted: 40,
    rejected: 15,
    rejectedPercentage: "27.27%",
  },
  {
    sNo: 4,
    date: "2024-04-04",
    totalEnquiries: 70,
    quoted: 50,
    rejected: 20,
    rejectedPercentage: "28.57%",
  },
  {
    sNo: 5,
    date: "2024-04-05",
    totalEnquiries: 65,
    quoted: 45,
    rejected: 20,
    rejectedPercentage: "30.77%",
  },
  {
    sNo: 6,
    date: "2024-04-06",
    totalEnquiries: 80,
    quoted: 60,
    rejected: 20,
    rejectedPercentage: "25%",
  },
  {
    sNo: 7,
    date: "2024-04-07",
    totalEnquiries: 90,
    quoted: 70,
    rejected: 20,
    rejectedPercentage: "22.22%",
  },
  {
    sNo: 8,
    date: "2024-04-08",
    totalEnquiries: 75,
    quoted: 50,
    rejected: 25,
    rejectedPercentage: "33.33%",
  },
  {
    sNo: 9,
    date: "2024-04-09",
    totalEnquiries: 85,
    quoted: 65,
    rejected: 20,
    rejectedPercentage: "23.53%",
  },
  {
    sNo: 10,
    date: "2024-04-10",
    totalEnquiries: 95,
    quoted: 80,
    rejected: 15,
    rejectedPercentage: "15.79%",
  },
];

export const trailTransactions = [
  {
    sno: 1,
    particle: "Commission Received",
    type: "credit",
    amount: "₹10,000",
    balance: "₹25,000",
  },
  {
    sno: 2,
    particle: "Client Payout",
    type: "debit",
    amount: "₹5,000",
    balance: "₹20,000",
  },
  {
    sno: 3,
    particle: "Referral Bonus",
    type: "credit",
    amount: "₹2,000",
    balance: "₹22,000",
  },
  {
    sno: 4,
    particle: "Office Rent",
    type: "debit",
    amount: "₹7,000",
    balance: "₹15,000",
  },
  {
    sno: 5,
    particle: "Stock Investment",
    type: "debit",
    amount: "₹8,000",
    balance: "₹7,000",
  },
  {
    sno: 6,
    particle: "Commission from Client A",
    type: "credit",
    amount: "₹15,000",
    balance: "₹22,000",
  },
  {
    sno: 7,
    particle: "Commission from Client B",
    type: "credit",
    amount: "₹12,000",
    balance: "₹34,000",
  },
  {
    sno: 8,
    particle: "Tax Payment",
    type: "debit",
    amount: "₹4,500",
    balance: "₹29,500",
  },
  {
    sno: 9,
    particle: "Consultation Fee",
    type: "credit",
    amount: "₹5,000",
    balance: "₹34,500",
  },
  {
    sno: 10,
    particle: "Operational Expenses",
    type: "debit",
    amount: "₹6,000",
    balance: "₹28,500",
  },
];

export const premiumTransactions = [
  {
    sno: 1,
    particle: "package",
    type: "credit",
    amount: "₹3000",
    balance: "₹3000",
  },
];

export const RoleData = [
  {
    sno: "1",
    name: "name",
    roles: "Admin",
    phonenumber: "7894561230",
    email: "test@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
];
